
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_chewallet
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

#services:
#  mysql:
#    image: mysql
#    restart: always
#    ports:
#      - 3308:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: db_aurynx
#      MYSQL_USER: dev_user
#      MYSQL_PASSWORD: secret
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#volumes:
#  mysql_data: